name: Django CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py check

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Create repo folder if not exists
            if [ ! -d "~/todo_ci-cd" ]; then
              git clone https://github.com/latifurrafi/todo_ci-cd.git ~/todo_ci-cd
            fi

            cd ~/todo_ci-cd

            # Pull latest code
            git fetch --all
            git reset --hard origin/main

            # Setup venv if not exists
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            
            # Upgrade pip and install dependencies
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt

            # Apply migrations
            python3 manage.py migrate

            # Restart Django
            pkill -f runserver || true
            nohup python3 manage.py runserver 0.0.0.0:8000 &


