name: Django CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py check

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Clone repo if missing
            if [ ! -d "$HOME/todo_ci-cd" ]; then
              git clone https://github.com/latifurrafi/todo_ci-cd.git $HOME/todo_ci-cd
            fi

            cd $HOME/todo_ci-cd
            # Pull latest code
            git fetch --all
            git reset --hard origin/main

            # Create venv if missing
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            # Upgrade pip & install dependencies
            $HOME/todo_ci-cd/venv/bin/python -m pip install --upgrade pip
            $HOME/todo_ci-cd/venv/bin/python -m pip install -r requirements.txt

            # Apply migrations
            $HOME/todo_ci-cd/venv/bin/python manage.py migrate

            # Restart systemd service
            sudo systemctl restart todo
