name: Django CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py check

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 1️⃣ Clone repo if missing
              if [ ! -d "$HOME/todo_ci-cd" ]; then
                git clone https://github.com/latifurrafi/todo_ci-cd.git $HOME/todo_ci-cd
              fi

              cd $HOME/todo_ci-cd

              # 2️⃣ Reset to latest main branch
              git fetch --all
              git reset --hard origin/main

              # 3️⃣ Create venv if missing
              if [ ! -d "venv" ]; then
                python3 -m venv venv
              fi

              # 4️⃣ Activate venv
              source venv/bin/activate

              # 5️⃣ Upgrade pip & install dependencies
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt

              # 6️⃣ Apply migrations
              python manage.py migrate

              # 7️⃣ Restart Django server
              pkill -f runserver || true
              nohup python manage.py runserver 0.0.0.0:8000 &

